### ISSUE TITLE
`tsort()` does not detect cycles of same node <-> child

### ISSUE THREAD

**Issue by lara** [ruby/tsort#4]
I expected the cycle in the following case (where `4 => [4]`) to be recognized, but it wasn't:

```
> g = {1=>[2, 3], 2=>[4], 3=>[2, 4], 4=>[4]}
=> {1=>[2, 3], 2=>[4], 3=>[2, 4], 4=>[4]}
> each_node = lambda { |&b| g.each_key(&b) }
=> #<Proc:0x00000001051a5be8 (irb):2 (lambda)>
> each_child = lambda { |n, &b| g[n].each(&b) }
=> #<Proc:0x000000010524f490 (irb):3 (lambda)>
> TSort.tsort(each_node, each_child)
=> [4, 2, 3, 1]
```

Verified the lambdas work for cycles such as `{2 => [4], 4=>[2]}`

**Comment by makenowjust** [comment]
I agree with you regarding it as a BUG. At least, we should notice this case in the `tsort` document.

**Comment by apainintheneck** [comment]
Isn't this similar to how the classic `tsort` command works?

> Presence of a node in a graph can be represented by an arc from the node to itself. This is useful when a node is not connected to any other nodes.

This is taken from the man page for the April 1, 1994 BSD version of `tsort` that ships with macOS Catalina.

**Comment by lara** [comment]
@apainintheneck ah, good point – I wasn't sure at first but I guess it means a self-loop is not considered a cycle until there is at least one more edge to create a "sequence"
