### ISSUE TITLE
Please clarify the license

### ISSUE THREAD

**Issue by voxik** [ruby/tsort#8]
The [license file](https://github.com/ruby/tsort/blob/master/LICENSE.txt) contains BSD-2-Clause license, while gemspec specifies [Ruby OR BSD-2-Clause](https://github.com/ruby/tsort/blob/2b3fe78646539a566f1d22c49e3d13daa1a3fa73/tsort.gemspec#L18). Assuming the latter is correct, how to capture this information? Is COPYING file similar to Ruby the way to go?

**Comment by hsbt** [comment]
Fixed at https://github.com/ruby/tsort/commit/a7188eacb9c1b861e83a0b562b025085df3f7b9f
